name: easy_animated_indexed_stack
description: "A drop-in replacement for Flutter's default IndexedStack widget that allows simple animations to transition between widgets"
version: 0.0.3
repository: https://github.com/shubhamsinghshubham777/easy_animated_indexed_stack

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
