name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
      - name: Publish to pub.dev
        run: dart pub publish -f
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
